### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by huynhtruc0309** [AccelAI/Mentor-Matching#19]
Can you please give some instruction to run this project? Thank you very much.

**Comment by TMcMac** [comment]
Hey Truc, so I wrote this specifically for LXAI so its a bit convoluted as it was tailored to their needs and the responses from their surveys. The entry point of the program is lxai_mentor_matcher.py and can be run with python3 -m lxai_mentor_matcher.py once you have installed the dependencies. That being said this needs to .xlsx spreadsheets with mentor and mentee data from the LXAI program to run and that is confidential information. If you want to talk about the project or ask any questions, feel free to email me at timmcmackenjr@gmail.com
